### ISSUE TITLE
mock服务无法随开发服务一起关闭，第二次开启会报端口占用错误

### ISSUE THREAD

**Issue by zhanghaoxu** [NervJS/taro-plugin-mock#1]
如题，期望的事 ctrl+c关闭开发服务的时候，mock服务会一同随开发服务关闭。

**Comment by fengfeng0603** [comment]
+1  不然这体验太差了

**Comment by 54853315** [comment]
+1，目前我是这样解决的：
```
sudo lsof -i tcp:9527
sudo kill -9 [pid]
```

**Comment by zhanghaoxu** [comment]
> +1，目前我是这样解决的：
> 
> ```
> sudo lsof -i tcp:9527
> sudo kill -9 [pid]
> ```
手动释放端口太麻烦了
解决方案的话 可以在写一个node脚本 使用 https://github.com/http-party/node-portfinder#readme 来做端口判断，然后通过写入一个环境变量标识是否端口占用（占用就认为mock服务已启动），然后启动开发服务，在配置项中通过环境变量来确定是否引入插件。
![Popo截图20201022105639](https://user-images.githubusercontent.com/10009567/96819048-51ad0000-1455-11eb-8dc2-b4b19a56da35.png)

**Comment by zxs-1024** [comment]
`kill -9 $(lsof -t -i :8081)`

**Comment by kinghoo5201** [comment]
`config/index.js` 加上下面逻辑
```js
const isAlipay = process.env.TARO_ENV === 'alipay';
const alipayPort = 9526;
const weappPort = 9527;
function portFix() {
  const port = isAlipay ? alipayPort : weappPort;
  const shellinfo = shelljs.exec(`lsof -i :${port}`).stdout.trim();
  const lineInfo = shellinfo.split('\n')[1];
  if (!lineInfo) {
    return;
  }
  const pid = lineInfo.split(/\s+/)[1];
  console.log(`监测到端口[port:${port}][pid:${pid}]，在运行,干掉！`);
  shelljs.exec(`kill -9 ${pid}`);
}
portFix();

```

可能有bug，但是大部分情况这样能解决的

**Comment by ctcx** [comment]
临时的解决方案是在 node_modules/@tarojs/plugin-mock/dist/indexe.js 第31行（await server.start() 下方）加上:
```
process.on('SIGINT', function () {
   console.log('数据 mock 服务已关闭.');
   process.exit();
});
```

**Comment by luckyadam** [comment]
最新版本解决了这个问题
