### ISSUE TITLE
在mock下配置了返回josn对象数据后返回不匹配

### ISSUE THREAD

**Issue by Grart** [NervJS/taro-plugin-mock#13]
在mock下配置了返回josn对象数据后返回不匹配。看了下utls.js文件，发现对象判断 string 和 funcon才有处理，否则就next了

![image](https://user-images.githubusercontent.com/6634875/142846783-cbc69069-19dc-4479-9bdc-cf82a2035a79.png)

**Comment by luckyadam** [comment]
来个 PR 咯

**Comment by EricWong1994** [comment]
> 来个 PR 咯

我提交PR了，可以过下

**Comment by EricWong1994** [comment]
> > 来个 PR 咯
> 
> 我提交PR了，可以过下

@luckyadam

**Comment by Chen-jj** [comment]
> > 我提交PR了，可以过下
> 
> @luckyadam

666~我们看看~
