### ISSUE TITLE
请问要如何匹配查询参数？

### ISSUE THREAD

**Issue by Codennnn** [NervJS/taro-plugin-mock#2]
接口带有查询参数时，不能正确匹配，能否使用正则表达式？

**Comment by mrdulin** [comment]
贴上你的API URL及查询参数，期望的结果，实际得到的结果

**Comment by saury** [comment]
参考这条[comment](https://github.com/NervJS/taro-plugin-mock/issues/18#issuecomment-1350747667)

**Comment by saury** [comment]
参考这条[comment](https://github.com/NervJS/taro-plugin-mock/issues/18#issuecomment-1350747667)
