### ISSUE TITLE
当指定host和port时，H5开发环境报跨域的错误

### ISSUE THREAD

**Issue by TimCN** [NervJS/taro-plugin-mock#5]
`config/dev.js`中的配置

```js
module.exports = {
  env: {
    NODE_ENV: '"development"',
  },
  plugins: [
    [
      "@tarojs/plugin-mock",
      {
        host: "localhost",
        port: 19090,
      },
    ],
  ],
  defineConstants: {},
  mini: {},
  h5: {},
};
```

通过 `npm run dev:h5` 跑出来的异常结果（跨域）如下：

![taro_issue](https://user-images.githubusercontent.com/10547628/120955849-e6663300-c784-11eb-9632-634b6e4c54b1.jpeg)

**Comment by TimCN** [comment]
通过拜读代码，发现在`Server`类中有`middlewares`的选项，目前我fork了一份代码，将其暴露出来是可以解决的

**Comment by luckyadam** [comment]
#7 这个 PR 解决了，可以升级到最新版本
